"""fix/fkeys

Revision ID: 1e0367198d2e
Revises: 8c39d76a9215
Create Date: 2026-06-28 12:37:14.202797

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1e0367198d2e"
down_revision: Union[str, Sequence[str], None] = "8c39d76a9215"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("meal_logs_meal_id_fkey"), "meal_logs", type_="foreignkey")
    op.drop_constraint(op.f("meal_logs_user_id_fkey"), "meal_logs", type_="foreignkey")
    op.create_foreign_key(
        None, "meal_logs", "meals", ["meal_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "meal_logs", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "meal_logs", type_="foreignkey")
    op.drop_constraint(None, "meal_logs", type_="foreignkey")
    op.create_foreign_key(
        op.f("meal_logs_user_id_fkey"), "meal_logs", "users", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("meal_logs_meal_id_fkey"), "meal_logs", "meals", ["meal_id"], ["id"]
    )
    # ### end Alembic commands ###
