"""update_users_notifications

Revision ID: 0f65a4337e84
Revises: a1b2c3d4e5f6
Create Date: 2026-06-19 21:19:52.494526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f65a4337e84'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notification_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('hard_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.drop_column('users', 'hard_mod')
    op.drop_column('users', 'notification_time')
    # ### end Alembic commands ###
