"""empty message

Revision ID: 89428300f1c9
Revises: 1e0367198d2e
Create Date: 2026-07-02 18:38:56.348172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89428300f1c9'
down_revision: Union[str, Sequence[str], None] = '1e0367198d2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'notification_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Time(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'notification_time',
               existing_type=sa.Time(timezone=True),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###
