[project]
name = "eat_log_bot"
version = "1.0.0"
requires-python = ">=3.14"
dependencies = [
    "aiogram>=3.28.2",
    "ariadne-codegen>=0.18.0",
]

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.mypy]
strict = true

[[tool.mypy.overrides]]
module = "src.graphql.*"
ignore_errors = true

[dependency-groups]
dev = [
    "mypy>=2.1.0",
    "ruff>=0.15.16",
]

[tool.ariadne-codegen]
remote_schema_url = "http://api:5285/graphql"
queries_path = "./src/graphql/"
target_package_path = "./src/graphql/"
target_package_name = "client"

[tool.ariadne-codegen.scalars.UUID]
type = "uuid.UUID"
