services:
  database:
    image: postgres:18.4
    container_name: eat_log_database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - "database_data:/var/lib/postgresql/"

  api:
    image: grachevnr/eat_log_api:latest
    container_name: eat_log_api
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      BOT_TOKEN: ${BOT_TOKEN}
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5285/health')"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  bot:
    image: grachevnr/eat_log_bot:latest
    container_name: eat_log_bot
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://api:5285/health')"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  schduler:
    image: grachevnr/eat_log_scheduler:latest
    container_name: eat_log_scheduler
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://api:5285/health')"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    depends_on:
      api:
        condition: service_healthy

  landing:
    image: grachevnr/eat_log_landing:latest
    container_name: eat_log_landing
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  caddy:
    image: grachevnr/eat_log_caddy:latest
    container_name: eat_log_caddy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      api:
        condition: service_healthy
      landing:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - caddy-data:/data/
      - caddy-config:/config/

volumes:
  database_data:
  caddy-data:
  caddy-config:
