query GetUserByTelegramId($telegramId: String!){
  userByTelegramId(
    telegramId: $telegramId,
  )
  {
    ... on User {
      ...UserFields
    }
    ... on ObjectNotFoundError {
      message
    }
  }
}
