# Generated by ariadne-codegen
# Source: ./src/graphql/

from typing import Any, Optional, Union

from .async_base_client import AsyncBaseClient
from .base_model import UNSET, UnsetType
from .get_users import GetUsers, GetUsersUsers
from .input_types import UsersFilterInput


def gql(q: str) -> str:
    return q


class Client(AsyncBaseClient):
    async def get_users(
        self,
        filter_: Union[Optional[UsersFilterInput], UnsetType] = UNSET,
        **kwargs: Any,
    ) -> list[GetUsersUsers]:
        query = gql("""
            query GetUsers($filter: UsersFilterInput) {
              users(filter: $filter) {
                ...UserFields
              }
            }

            fragment UserFields on User {
              telegramId
              name
            }
            """)
        variables: dict[str, object] = {"filter": filter_}
        response = await self.execute(
            query=query, operation_name="GetUsers", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetUsers.model_validate(data).users
