# Generated by ariadne-codegen
# Source: ./src/graphql/

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class UserFields(BaseModel):
    telegram_id: Optional[str] = Field(alias="telegramId")
    name: str


UserFields.model_rebuild()
