# Generated by ariadne-codegen
# Source: ./src/graphql/

from .base_model import BaseModel
from .fragments import UserFields


class Users(BaseModel):
    users: list["UsersUsers"]


class UsersUsers(UserFields):
    pass


Users.model_rebuild()
