# Generated by ariadne-codegen

from .async_base_client import AsyncBaseClient
from .base_model import BaseModel, Upload
from .client import Client
from .create_meal import (
    CreateMeal,
    CreateMealCreateMealMeal,
    CreateMealCreateMealObjectAlreadyExistsError,
)
from .create_meal_log import (
    CreateMealLog,
    CreateMealLogCreateMealLogMealLog,
    CreateMealLogCreateMealLogObjectNotFoundError,
)
from .create_user import CreateUser, CreateUserCreateUser
from .delete_meal_log import DeleteMealLog
from .enums import Gender, Goal
from .exceptions import (
    GraphQLClientError,
    GraphQLClientGraphQLError,
    GraphQLClientGraphQLMultiError,
    GraphQLClientHttpError,
    GraphQLClientInvalidResponseError,
)
from .fragments import (
    MealFields,
    MealLogFields,
    MealLogFieldsMeal,
    MealLogFieldsUser,
    UserFields,
)
from .get_meal_logs import GetMealLogs, GetMealLogsMealLogs
from .get_meals import GetMeals, GetMealsMeals
from .get_user import GetUser, GetUserUserObjectNotFoundError, GetUserUserUser
from .get_user_by_telegram_id import (
    GetUserByTelegramId,
    GetUserByTelegramIdUserByTelegramIdObjectNotFoundError,
    GetUserByTelegramIdUserByTelegramIdUser,
)
from .get_users import GetUsers, GetUsersUsers
from .input_types import (
    CreateMealInput,
    CreateMealLogInput,
    CreateUserInput,
    MealFilters,
    MealLogFilter,
    UpdateMealLogInput,
    UpdateUserInput,
    UsersFilterInput,
)
from .update_meal_log import (
    UpdateMealLog,
    UpdateMealLogUpdateMealLogMealLog,
    UpdateMealLogUpdateMealLogObjectNotFoundError,
)
from .update_user import (
    UpdateUser,
    UpdateUserUpdateUserObjectNotFoundError,
    UpdateUserUpdateUserUser,
)

__all__ = [
    "AsyncBaseClient",
    "BaseModel",
    "Client",
    "CreateMeal",
    "CreateMealCreateMealMeal",
    "CreateMealCreateMealObjectAlreadyExistsError",
    "CreateMealInput",
    "CreateMealLog",
    "CreateMealLogCreateMealLogMealLog",
    "CreateMealLogCreateMealLogObjectNotFoundError",
    "CreateMealLogInput",
    "CreateUser",
    "CreateUserCreateUser",
    "CreateUserInput",
    "DeleteMealLog",
    "Gender",
    "GetMealLogs",
    "GetMealLogsMealLogs",
    "GetMeals",
    "GetMealsMeals",
    "GetUser",
    "GetUserByTelegramId",
    "GetUserByTelegramIdUserByTelegramIdObjectNotFoundError",
    "GetUserByTelegramIdUserByTelegramIdUser",
    "GetUserUserObjectNotFoundError",
    "GetUserUserUser",
    "GetUsers",
    "GetUsersUsers",
    "Goal",
    "GraphQLClientError",
    "GraphQLClientGraphQLError",
    "GraphQLClientGraphQLMultiError",
    "GraphQLClientHttpError",
    "GraphQLClientInvalidResponseError",
    "MealFields",
    "MealFilters",
    "MealLogFields",
    "MealLogFieldsMeal",
    "MealLogFieldsUser",
    "MealLogFilter",
    "UpdateMealLog",
    "UpdateMealLogInput",
    "UpdateMealLogUpdateMealLogMealLog",
    "UpdateMealLogUpdateMealLogObjectNotFoundError",
    "UpdateUser",
    "UpdateUserInput",
    "UpdateUserUpdateUserObjectNotFoundError",
    "UpdateUserUpdateUserUser",
    "Upload",
    "UserFields",
    "UsersFilterInput",
]
