# Generated by ariadne-codegen
# Source: ./src/gql/

from typing import Any, Optional, Union
from uuid import UUID

from .async_base_client import AsyncBaseClient
from .base_model import UNSET, UnsetType
from .create_meal import (
    CreateMeal,
    CreateMealCreateMealMeal,
    CreateMealCreateMealObjectAlreadyExistsError,
)
from .create_meal_log import (
    CreateMealLog,
    CreateMealLogCreateMealLogMealLog,
    CreateMealLogCreateMealLogObjectNotFoundError,
)
from .create_user import CreateUser, CreateUserCreateUser
from .delete_meal_log import DeleteMealLog
from .get_meal_logs import GetMealLogs, GetMealLogsMealLogs
from .get_meals import GetMeals, GetMealsMeals
from .get_user import GetUser, GetUserUserObjectNotFoundError, GetUserUserUser
from .get_user_by_telegram_id import (
    GetUserByTelegramId,
    GetUserByTelegramIdUserByTelegramIdObjectNotFoundError,
    GetUserByTelegramIdUserByTelegramIdUser,
)
from .get_users import GetUsers, GetUsersUsers
from .input_types import (
    CreateMealInput,
    CreateMealLogInput,
    CreateUserInput,
    MealFilters,
    MealLogFilter,
    UpdateMealLogInput,
    UpdateUserInput,
    UsersFilterInput,
)
from .update_meal_log import (
    UpdateMealLog,
    UpdateMealLogUpdateMealLogMealLog,
    UpdateMealLogUpdateMealLogObjectNotFoundError,
)
from .update_user import (
    UpdateUser,
    UpdateUserUpdateUserObjectNotFoundError,
    UpdateUserUpdateUserUser,
)


def gql(q: str) -> str:
    return q


class Client(AsyncBaseClient):
    async def create_meal_log(
        self, input: CreateMealLogInput, **kwargs: Any
    ) -> Union[
        CreateMealLogCreateMealLogMealLog, CreateMealLogCreateMealLogObjectNotFoundError
    ]:
        query = gql("""
            mutation CreateMealLog($input: CreateMealLogInput!) {
              createMealLog(input: $input) {
                __typename
                ... on MealLog {
                  ...MealLogFields
                }
                ... on ObjectNotFoundError {
                  message
                }
              }
            }

            fragment MealFields on Meal {
              id
              title
              calories
              protein
              fat
              carbohydrate
            }

            fragment MealLogFields on MealLog {
              id
              grams
              createdAt
              updatedAt
              user {
                ...UserFields
              }
              meal {
                ...MealFields
              }
            }

            fragment UserFields on User {
              id
              name
              telegramId
              gender
              weight
              height
              age
              goal
              notificationTime
              hardMod
            }
            """)
        variables: dict[str, object] = {"input": input}
        response = await self.execute(
            query=query, operation_name="CreateMealLog", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return CreateMealLog.model_validate(data).create_meal_log

    async def delete_meal_log(self, id: int, **kwargs: Any) -> Optional[Any]:
        query = gql("""
            mutation DeleteMealLog($id: Int!) {
              deleteMealLog(id: $id)
            }
            """)
        variables: dict[str, object] = {"id": id}
        response = await self.execute(
            query=query, operation_name="DeleteMealLog", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return DeleteMealLog.model_validate(data).delete_meal_log

    async def update_meal_log(
        self, id: int, input: UpdateMealLogInput, **kwargs: Any
    ) -> Union[
        UpdateMealLogUpdateMealLogMealLog, UpdateMealLogUpdateMealLogObjectNotFoundError
    ]:
        query = gql("""
            mutation UpdateMealLog($id: Int!, $input: UpdateMealLogInput!) {
              updateMealLog(id: $id, input: $input) {
                __typename
                ... on MealLog {
                  ...MealLogFields
                }
                ... on ObjectNotFoundError {
                  message
                }
              }
            }

            fragment MealFields on Meal {
              id
              title
              calories
              protein
              fat
              carbohydrate
            }

            fragment MealLogFields on MealLog {
              id
              grams
              createdAt
              updatedAt
              user {
                ...UserFields
              }
              meal {
                ...MealFields
              }
            }

            fragment UserFields on User {
              id
              name
              telegramId
              gender
              weight
              height
              age
              goal
              notificationTime
              hardMod
            }
            """)
        variables: dict[str, object] = {"id": id, "input": input}
        response = await self.execute(
            query=query, operation_name="UpdateMealLog", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return UpdateMealLog.model_validate(data).update_meal_log

    async def create_meal(
        self, input: CreateMealInput, **kwargs: Any
    ) -> Union[CreateMealCreateMealMeal, CreateMealCreateMealObjectAlreadyExistsError]:
        query = gql("""
            mutation CreateMeal($input: CreateMealInput!) {
              createMeal(input: $input) {
                __typename
                ... on Meal {
                  ...MealFields
                }
                ... on ObjectAlreadyExistsError {
                  message
                }
              }
            }

            fragment MealFields on Meal {
              id
              title
              calories
              protein
              fat
              carbohydrate
            }
            """)
        variables: dict[str, object] = {"input": input}
        response = await self.execute(
            query=query, operation_name="CreateMeal", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return CreateMeal.model_validate(data).create_meal

    async def create_user(
        self, input: CreateUserInput, **kwargs: Any
    ) -> CreateUserCreateUser:
        query = gql("""
            mutation CreateUser($input: CreateUserInput!) {
              createUser(input: $input) {
                ...UserFields
              }
            }

            fragment UserFields on User {
              id
              name
              telegramId
              gender
              weight
              height
              age
              goal
              notificationTime
              hardMod
            }
            """)
        variables: dict[str, object] = {"input": input}
        response = await self.execute(
            query=query, operation_name="CreateUser", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return CreateUser.model_validate(data).create_user

    async def update_user(
        self, id: UUID, input: UpdateUserInput, **kwargs: Any
    ) -> Union[UpdateUserUpdateUserUser, UpdateUserUpdateUserObjectNotFoundError]:
        query = gql("""
            mutation UpdateUser($id: UUID!, $input: UpdateUserInput!) {
              updateUser(id: $id, input: $input) {
                __typename
                ... on User {
                  ...UserFields
                }
                ... on ObjectNotFoundError {
                  message
                }
              }
            }

            fragment UserFields on User {
              id
              name
              telegramId
              gender
              weight
              height
              age
              goal
              notificationTime
              hardMod
            }
            """)
        variables: dict[str, object] = {"id": id, "input": input}
        response = await self.execute(
            query=query, operation_name="UpdateUser", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return UpdateUser.model_validate(data).update_user

    async def get_meal_logs(
        self,
        filter_: Union[Optional[MealLogFilter], UnsetType] = UNSET,
        limit: Union[Optional[int], UnsetType] = UNSET,
        offset: Union[Optional[int], UnsetType] = UNSET,
        **kwargs: Any,
    ) -> list[GetMealLogsMealLogs]:
        query = gql("""
            query GetMealLogs($filter: MealLogFilter, $limit: Int, $offset: Int) {
              mealLogs(filter: $filter, limit: $limit, offset: $offset) {
                ...MealLogFields
              }
            }

            fragment MealFields on Meal {
              id
              title
              calories
              protein
              fat
              carbohydrate
            }

            fragment MealLogFields on MealLog {
              id
              grams
              createdAt
              updatedAt
              user {
                ...UserFields
              }
              meal {
                ...MealFields
              }
            }

            fragment UserFields on User {
              id
              name
              telegramId
              gender
              weight
              height
              age
              goal
              notificationTime
              hardMod
            }
            """)
        variables: dict[str, object] = {
            "filter": filter_,
            "limit": limit,
            "offset": offset,
        }
        response = await self.execute(
            query=query, operation_name="GetMealLogs", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetMealLogs.model_validate(data).meal_logs

    async def get_meals(
        self,
        filter_: Union[Optional[MealFilters], UnsetType] = UNSET,
        limit: Union[Optional[int], UnsetType] = UNSET,
        offset: Union[Optional[int], UnsetType] = UNSET,
        **kwargs: Any,
    ) -> list[GetMealsMeals]:
        query = gql("""
            query GetMeals($filter: MealFilters, $limit: Int, $offset: Int) {
              meals(filter: $filter, limit: $limit, offset: $offset) {
                ...MealFields
              }
            }

            fragment MealFields on Meal {
              id
              title
              calories
              protein
              fat
              carbohydrate
            }
            """)
        variables: dict[str, object] = {
            "filter": filter_,
            "limit": limit,
            "offset": offset,
        }
        response = await self.execute(
            query=query, operation_name="GetMeals", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetMeals.model_validate(data).meals

    async def get_user(
        self, id: UUID, **kwargs: Any
    ) -> Union[GetUserUserUser, GetUserUserObjectNotFoundError]:
        query = gql("""
            query GetUser($id: UUID!) {
              user(id: $id) {
                __typename
                ... on User {
                  ...UserFields
                }
                ... on ObjectNotFoundError {
                  message
                }
              }
            }

            fragment UserFields on User {
              id
              name
              telegramId
              gender
              weight
              height
              age
              goal
              notificationTime
              hardMod
            }
            """)
        variables: dict[str, object] = {"id": id}
        response = await self.execute(
            query=query, operation_name="GetUser", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetUser.model_validate(data).user

    async def get_user_by_telegram_id(
        self, telegram_id: str, **kwargs: Any
    ) -> Union[
        GetUserByTelegramIdUserByTelegramIdUser,
        GetUserByTelegramIdUserByTelegramIdObjectNotFoundError,
    ]:
        query = gql("""
            query GetUserByTelegramId($telegramId: String!) {
              userByTelegramId(telegramId: $telegramId) {
                __typename
                ... on User {
                  ...UserFields
                }
                ... on ObjectNotFoundError {
                  message
                }
              }
            }

            fragment UserFields on User {
              id
              name
              telegramId
              gender
              weight
              height
              age
              goal
              notificationTime
              hardMod
            }
            """)
        variables: dict[str, object] = {"telegramId": telegram_id}
        response = await self.execute(
            query=query,
            operation_name="GetUserByTelegramId",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return GetUserByTelegramId.model_validate(data).user_by_telegram_id

    async def get_users(
        self,
        filter_: Union[Optional[UsersFilterInput], UnsetType] = UNSET,
        **kwargs: Any,
    ) -> list[GetUsersUsers]:
        query = gql("""
            query GetUsers($filter: UsersFilterInput) {
              users(filter: $filter) {
                ...UserFields
              }
            }

            fragment UserFields on User {
              id
              name
              telegramId
              gender
              weight
              height
              age
              goal
              notificationTime
              hardMod
            }
            """)
        variables: dict[str, object] = {"filter": filter_}
        response = await self.execute(
            query=query, operation_name="GetUsers", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetUsers.model_validate(data).users
