# Generated by ariadne-codegen
# Source: ./src/gql/

from typing import Literal, Union

from pydantic import Field

from .base_model import BaseModel
from .fragments import MealLogFields


class CreateMealLog(BaseModel):
    create_meal_log: Union[
        "CreateMealLogCreateMealLogMealLog",
        "CreateMealLogCreateMealLogObjectNotFoundError",
    ] = Field(alias="createMealLog", discriminator="typename__")


class CreateMealLogCreateMealLogMealLog(MealLogFields):
    typename__: Literal["MealLog"] = Field(alias="__typename")


class CreateMealLogCreateMealLogObjectNotFoundError(BaseModel):
    typename__: Literal["ObjectNotFoundError"] = Field(alias="__typename")
    message: str


CreateMealLog.model_rebuild()
