# Generated by ariadne-codegen
# Source: ./src/gql/

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class DeleteMealLog(BaseModel):
    delete_meal_log: Optional[Any] = Field(alias="deleteMealLog")
