# Generated by ariadne-codegen
# Source: ./../../server/api/server-schema.gql

from enum import Enum


class Gender(str, Enum):
    MALE = "MALE"
    FEMALE = "FEMALE"


class Goal(str, Enum):
    MAINTAIN = "MAINTAIN"
    LOSE = "LOSE"
    GAIN = "GAIN"
