# Generated by ariadne-codegen
# Source: ./src/gql/

from typing import Literal, Union

from pydantic import Field

from .base_model import BaseModel
from .fragments import UserFields


class GetUserByTelegramId(BaseModel):
    user_by_telegram_id: Union[
        "GetUserByTelegramIdUserByTelegramIdUser",
        "GetUserByTelegramIdUserByTelegramIdObjectNotFoundError",
    ] = Field(alias="userByTelegramId", discriminator="typename__")


class GetUserByTelegramIdUserByTelegramIdUser(UserFields):
    typename__: Literal["User"] = Field(alias="__typename")


class GetUserByTelegramIdUserByTelegramIdObjectNotFoundError(BaseModel):
    typename__: Literal["ObjectNotFoundError"] = Field(alias="__typename")
    message: str


GetUserByTelegramId.model_rebuild()
