# Generated by ariadne-codegen
# Source: ./src/gql/

from .base_model import BaseModel
from .fragments import MealFields


class GetMeals(BaseModel):
    meals: list["GetMealsMeals"]


class GetMealsMeals(MealFields):
    pass


GetMeals.model_rebuild()
