# Generated by ariadne-codegen
# Source: ./src/gql/

from .base_model import BaseModel
from .fragments import UserFields


class GetUsers(BaseModel):
    users: list["GetUsersUsers"]


class GetUsersUsers(UserFields):
    pass


GetUsers.model_rebuild()
