# Generated by ariadne-codegen
# Source: ./src/gql/

from pydantic import Field

from .base_model import BaseModel
from .fragments import MealLogFields


class GetMealLogs(BaseModel):
    meal_logs: list["GetMealLogsMealLogs"] = Field(alias="mealLogs")


class GetMealLogsMealLogs(MealLogFields):
    pass


GetMealLogs.model_rebuild()
