# Generated by ariadne-codegen
# Source: ./../../server/api/server-schema.gql

from datetime import date, time
from typing import Optional
from uuid import UUID

from pydantic import Field

from .base_model import BaseModel
from .enums import Gender, Goal


class CreateMealInput(BaseModel):
    title: str
    calories: float
    protein: float
    fat: float
    carbohydrate: float


class CreateMealLogInput(BaseModel):
    user_id: UUID = Field(alias="userId")
    meal_id: int = Field(alias="mealId")
    grams: float


class CreateUserInput(BaseModel):
    name: str
    telegram_id: Optional[str] = Field(alias="telegramId", default=None)
    gender: Gender
    weight: float
    height: float
    age: int
    goal: Goal
    notification_time: Optional[time] = Field(alias="notificationTime", default=None)
    hard_mod: bool = Field(alias="hardMod", default=False)


class MealFilters(BaseModel):
    search_query: Optional[str] = Field(alias="searchQuery", default=None)


class MealLogFilter(BaseModel):
    user_id: Optional[UUID] = Field(alias="userId", default=None)
    date_filter: Optional[date] = Field(alias="dateFilter", default=None)


class UpdateMealLogInput(BaseModel):
    user_id: Optional[UUID] = Field(alias="userId", default=None)
    meal_id: Optional[int] = Field(alias="mealId", default=None)
    grams: Optional[float] = None


class UpdateUserInput(BaseModel):
    name: Optional[str] = None
    telegram_id: Optional[str] = Field(alias="telegramId", default=None)
    gender: Optional[Gender] = None
    weight: Optional[float] = None
    height: Optional[float] = None
    age: Optional[int] = None
    goal: Optional[Goal] = None
    notification_time: Optional[time] = Field(alias="notificationTime", default=None)
    hard_mod: Optional[bool] = Field(alias="hardMod", default=None)


class UsersFilterInput(BaseModel):
    without_logs_on: Optional[date] = Field(alias="withoutLogsOn", default=None)
    notification_time: Optional[time] = Field(alias="notificationTime", default=None)
    telegram_id_exists: Optional[bool] = Field(alias="telegramIdExists", default=None)
