# Generated by ariadne-codegen
# Source: ./src/graphql/

from typing import Optional
from uuid import UUID

from pydantic import Field

from .base_model import BaseModel


class UserFields(BaseModel):
    id: UUID
    name: str
    telegram_id: Optional[str] = Field(alias="telegramId")


UserFields.model_rebuild()
