# Generated by ariadne-codegen
# Source: ./src/graphql/

from datetime import time
from typing import Optional
from uuid import UUID

from pydantic import Field

from .base_model import BaseModel


class UserFields(BaseModel):
    id: UUID
    name: str
    telegram_id: Optional[str] = Field(alias="telegramId")
    notification_time: Optional[time] = Field(alias="notificationTime")
    hard_mod: bool = Field(alias="hardMod")


UserFields.model_rebuild()
