# Generated by ariadne-codegen
# Source: http://api:5285/graphql

from datetime import datetime
from typing import Any, Optional
from uuid import UUID

from pydantic import Field

from .base_model import BaseModel
from .enums import Gender, Goal


class MealFilters(BaseModel):
    search_query: Optional[str] = Field(alias="searchQuery", default=None)


class MealLogFilter(BaseModel):
    user_id: Optional[UUID] = Field(alias="userId", default=None)
    date_filter: Optional[Any] = Field(alias="dateFilter", default=None)


class CreateUserInput(BaseModel):
    name: str
    telegram_id: Optional[str] = Field(alias="telegramId", default=None)
    gender: Gender
    weight: float
    height: float
    age: int
    goal: Goal
    notification_time: Optional[datetime] = Field(
        alias="notificationTime", default=None
    )
    hard_mod: bool = Field(alias="hardMod")


class UpdateUserInput(BaseModel):
    name: Optional[str] = None
    telegram_id: Optional[str] = Field(alias="telegramId", default=None)
    gender: Optional[Gender] = None
    weight: Optional[float] = None
    height: Optional[float] = None
    age: Optional[int] = None
    goal: Optional[Goal] = None
    notification_time: Optional[datetime] = Field(
        alias="notificationTime", default=None
    )
    hard_mod: Optional[bool] = Field(alias="hardMod", default=None)


class CreateMealInput(BaseModel):
    title: str
    calories: float
    protein: float
    fat: float
    carbohydrate: float


class CreateMealLogInput(BaseModel):
    user_id: UUID = Field(alias="userId")
    meal_id: int = Field(alias="mealId")
    grams: float


class UpdateMealLogInput(BaseModel):
    user_id: Optional[UUID] = Field(alias="userId", default=None)
    meal_id: Optional[int] = Field(alias="mealId", default=None)
    grams: Optional[float] = None
