# Generated by ariadne-codegen
# Source: ./src/graphql/

from typing import Literal, Union

from pydantic import Field

from .base_model import BaseModel
from .fragments import UserFields


class UpdateUser(BaseModel):
    update_user: Union[
        "UpdateUserUpdateUserUser", "UpdateUserUpdateUserObjectNotFoundError"
    ] = Field(alias="updateUser", discriminator="typename__")


class UpdateUserUpdateUserUser(UserFields):
    typename__: Literal["User"] = Field(alias="__typename")


class UpdateUserUpdateUserObjectNotFoundError(BaseModel):
    typename__: Literal["ObjectNotFoundError"] = Field(alias="__typename")
    message: str


UpdateUser.model_rebuild()
