server {
    listen 80;
    listen [::]:80;
    server_name api.eat-log.ru;

    location / {
        proxy_pass http://api:5285;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name eat-log.ru;

    location / {
        proxy_pass http://web:80;
    }
}

server {
    listen 80;
    listen [::]:80;

    location /health {
        access_log off;
        return 200 "ok\n";
    }
}
