services:
  api:
    image: grachevnr/eat_log_api:latest
    container_name: eat_log_api
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      BOT_TOKEN: ${BOT_TOKEN}
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5285/health')"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  bot:
    image: grachevnr/eat_log_bot:latest
    container_name: eat_log_bot
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://api:5285/health')"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  schduler:
    image: grachevnr/eat_log_scheduler:latest
    container_name: eat_log_scheduler
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://api:5285/health')"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    depends_on:
      api:
        condition: service_healthy

  web:
    image: grachevnr/eat_log_web:latest
    container_name: eat_log_web
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  caddy:
    image: grachevnr/eat_log_caddy:latest
    container_name: eat_log_caddy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      api:
        condition: service_healthy
      web:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
