# Generated by ariadne-codegen
# Source: ./src/graphql/

from typing import Any, Optional, Union
from uuid import UUID

from .async_base_client import AsyncBaseClient
from .base_model import UNSET, UnsetType
from .create_meal import CreateMeal
from .create_meal_log import CreateMealLog
from .create_user import CreateUser
from .delete_meal_log import DeleteMealLog
from .get_user import GetUser
from .input_types import (
    CreateMealInput,
    CreateMealLogInput,
    CreateUserInput,
    MealFilters,
    MealLogFilter,
    UpdateMealLogInput,
    UpdateUserInput,
)
from .meal_logs import MealLogs
from .meals import Meals
from .update_meal_log import UpdateMealLog
from .update_user import UpdateUser


def gql(q: str) -> str:
    return q


class Client(AsyncBaseClient):
    async def create_meal_log(
        self, input: CreateMealLogInput, **kwargs: Any
    ) -> CreateMealLog:
        query = gql("""
            mutation CreateMealLog($input: CreateMealLogInput!) {
              createMealLog(input: $input) {
                __typename
                ... on MealLog {
                  ...MealLogFields
                }
                ... on ObjectNotFoundError {
                  message
                }
              }
            }

            fragment MealFields on Meal {
              id
              title
              calories
              protein
              fat
              carbohydrate
            }

            fragment MealLogFields on MealLog {
              id
              grams
              createdAt
              updatedAt
              user {
                ...UserFields
              }
              meal {
                ...MealFields
              }
            }

            fragment UserFields on User {
              id
              name
              telegramId
              gender
              weight
              height
              age
              goal
              notificationTime
              hardMod
            }
            """)
        variables: dict[str, object] = {"input": input}
        response = await self.execute(
            query=query, operation_name="CreateMealLog", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return CreateMealLog.model_validate(data)

    async def delete_meal_log(self, id: int, **kwargs: Any) -> DeleteMealLog:
        query = gql("""
            mutation DeleteMealLog($id: Int!) {
              deleteMealLog(id: $id)
            }
            """)
        variables: dict[str, object] = {"id": id}
        response = await self.execute(
            query=query, operation_name="DeleteMealLog", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return DeleteMealLog.model_validate(data)

    async def update_meal_log(
        self, id: int, input: UpdateMealLogInput, **kwargs: Any
    ) -> UpdateMealLog:
        query = gql("""
            mutation UpdateMealLog($id: Int!, $input: UpdateMealLogInput!) {
              updateMealLog(id: $id, input: $input) {
                __typename
                ... on MealLog {
                  ...MealLogFields
                }
                ... on ObjectNotFoundError {
                  message
                }
              }
            }

            fragment MealFields on Meal {
              id
              title
              calories
              protein
              fat
              carbohydrate
            }

            fragment MealLogFields on MealLog {
              id
              grams
              createdAt
              updatedAt
              user {
                ...UserFields
              }
              meal {
                ...MealFields
              }
            }

            fragment UserFields on User {
              id
              name
              telegramId
              gender
              weight
              height
              age
              goal
              notificationTime
              hardMod
            }
            """)
        variables: dict[str, object] = {"id": id, "input": input}
        response = await self.execute(
            query=query, operation_name="UpdateMealLog", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return UpdateMealLog.model_validate(data)

    async def create_meal(self, input: CreateMealInput, **kwargs: Any) -> CreateMeal:
        query = gql("""
            mutation CreateMeal($input: CreateMealInput!) {
              createMeal(input: $input) {
                __typename
                ... on Meal {
                  ...MealFields
                }
                ... on ObjectAlreadyExistsError {
                  message
                }
              }
            }

            fragment MealFields on Meal {
              id
              title
              calories
              protein
              fat
              carbohydrate
            }
            """)
        variables: dict[str, object] = {"input": input}
        response = await self.execute(
            query=query, operation_name="CreateMeal", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return CreateMeal.model_validate(data)

    async def create_user(self, input: CreateUserInput, **kwargs: Any) -> CreateUser:
        query = gql("""
            mutation CreateUser($input: CreateUserInput!) {
              createUser(input: $input) {
                ...UserFields
              }
            }

            fragment UserFields on User {
              id
              name
              telegramId
              gender
              weight
              height
              age
              goal
              notificationTime
              hardMod
            }
            """)
        variables: dict[str, object] = {"input": input}
        response = await self.execute(
            query=query, operation_name="CreateUser", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return CreateUser.model_validate(data)

    async def update_user(
        self, id: UUID, input: UpdateUserInput, **kwargs: Any
    ) -> UpdateUser:
        query = gql("""
            mutation UpdateUser($id: UUID!, $input: UpdateUserInput!) {
              updateUser(id: $id, input: $input) {
                __typename
                ... on User {
                  ...UserFields
                }
                ... on ObjectNotFoundError {
                  message
                }
              }
            }

            fragment UserFields on User {
              id
              name
              telegramId
              gender
              weight
              height
              age
              goal
              notificationTime
              hardMod
            }
            """)
        variables: dict[str, object] = {"id": id, "input": input}
        response = await self.execute(
            query=query, operation_name="UpdateUser", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return UpdateUser.model_validate(data)

    async def meal_logs(
        self,
        filter_: Union[Optional[MealLogFilter], UnsetType] = UNSET,
        limit: Union[Optional[int], UnsetType] = UNSET,
        offset: Union[Optional[int], UnsetType] = UNSET,
        **kwargs: Any,
    ) -> MealLogs:
        query = gql("""
            query MealLogs($filter: MealLogFilter, $limit: Int, $offset: Int) {
              mealLogs(filter: $filter, limit: $limit, offset: $offset) {
                ...MealLogFields
              }
            }

            fragment MealFields on Meal {
              id
              title
              calories
              protein
              fat
              carbohydrate
            }

            fragment MealLogFields on MealLog {
              id
              grams
              createdAt
              updatedAt
              user {
                ...UserFields
              }
              meal {
                ...MealFields
              }
            }

            fragment UserFields on User {
              id
              name
              telegramId
              gender
              weight
              height
              age
              goal
              notificationTime
              hardMod
            }
            """)
        variables: dict[str, object] = {
            "filter": filter_,
            "limit": limit,
            "offset": offset,
        }
        response = await self.execute(
            query=query, operation_name="MealLogs", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return MealLogs.model_validate(data)

    async def meals(
        self,
        filter_: Union[Optional[MealFilters], UnsetType] = UNSET,
        limit: Union[Optional[int], UnsetType] = UNSET,
        offset: Union[Optional[int], UnsetType] = UNSET,
        **kwargs: Any,
    ) -> Meals:
        query = gql("""
            query Meals($filter: MealFilters, $limit: Int, $offset: Int) {
              meals(filter: $filter, limit: $limit, offset: $offset) {
                ...MealFields
              }
            }

            fragment MealFields on Meal {
              id
              title
              calories
              protein
              fat
              carbohydrate
            }
            """)
        variables: dict[str, object] = {
            "filter": filter_,
            "limit": limit,
            "offset": offset,
        }
        response = await self.execute(
            query=query, operation_name="Meals", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return Meals.model_validate(data)

    async def get_user(self, id: UUID, **kwargs: Any) -> GetUser:
        query = gql("""
            query GetUser($id: UUID!) {
              user(id: $id) {
                __typename
                ... on User {
                  ...UserFields
                }
                ... on ObjectNotFoundError {
                  message
                }
              }
            }

            fragment UserFields on User {
              id
              name
              telegramId
              gender
              weight
              height
              age
              goal
              notificationTime
              hardMod
            }
            """)
        variables: dict[str, object] = {"id": id}
        response = await self.execute(
            query=query, operation_name="GetUser", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetUser.model_validate(data)
