# Generated by ariadne-codegen
# Source: ./src/graphql/

from typing import Literal, Union

from pydantic import Field

from .base_model import BaseModel
from .fragments import MealFields


class CreateMeal(BaseModel):
    create_meal: Union[
        "CreateMealCreateMealMeal", "CreateMealCreateMealObjectAlreadyExistsError"
    ] = Field(alias="createMeal", discriminator="typename__")


class CreateMealCreateMealMeal(MealFields):
    typename__: Literal["Meal"] = Field(alias="__typename")


class CreateMealCreateMealObjectAlreadyExistsError(BaseModel):
    typename__: Literal["ObjectAlreadyExistsError"] = Field(alias="__typename")
    message: str


CreateMeal.model_rebuild()
