# Generated by ariadne-codegen
# Source: http://localhost:5285/graphql

from enum import Enum


class Gender(str, Enum):
    MALE = "MALE"
    FEMALE = "FEMALE"


class Goal(str, Enum):
    MAINTAIN = "MAINTAIN"
    LOSE = "LOSE"
    GAIN = "GAIN"
