# Generated by ariadne-codegen
# Source: ./src/graphql/

from datetime import datetime, time
from typing import Optional
from uuid import UUID

from pydantic import Field

from .base_model import BaseModel
from .enums import Gender, Goal


class MealFields(BaseModel):
    id: int
    title: str
    calories: float
    protein: float
    fat: float
    carbohydrate: float


class UserFields(BaseModel):
    id: UUID
    name: str
    telegram_id: Optional[str] = Field(alias="telegramId")
    gender: Gender
    weight: float
    height: float
    age: int
    goal: Goal
    notification_time: Optional[time] = Field(alias="notificationTime")
    hard_mod: bool = Field(alias="hardMod")


class MealLogFields(BaseModel):
    id: int
    grams: float
    created_at: datetime = Field(alias="createdAt")
    updated_at: datetime = Field(alias="updatedAt")
    user: "MealLogFieldsUser"
    meal: "MealLogFieldsMeal"


class MealLogFieldsUser(UserFields):
    pass


class MealLogFieldsMeal(MealFields):
    pass


MealFields.model_rebuild()
UserFields.model_rebuild()
MealLogFields.model_rebuild()
