# Generated by ariadne-codegen
# Source: ./src/graphql/

from typing import Literal, Union

from pydantic import Field

from .base_model import BaseModel
from .fragments import UserFields


class GetUser(BaseModel):
    user: Union["GetUserUserUser", "GetUserUserObjectNotFoundError"] = Field(
        discriminator="typename__"
    )


class GetUserUserUser(UserFields):
    typename__: Literal["User"] = Field(alias="__typename")


class GetUserUserObjectNotFoundError(BaseModel):
    typename__: Literal["ObjectNotFoundError"] = Field(alias="__typename")
    message: str


GetUser.model_rebuild()
