# Generated by ariadne-codegen
# Source: ./src/graphql/

from pydantic import Field

from .base_model import BaseModel
from .fragments import MealLogFields


class MealLogs(BaseModel):
    meal_logs: list["MealLogsMealLogs"] = Field(alias="mealLogs")


class MealLogsMealLogs(MealLogFields):
    pass


MealLogs.model_rebuild()
