# Generated by ariadne-codegen
# Source: ./src/graphql/

from .base_model import BaseModel
from .fragments import MealFields


class Meals(BaseModel):
    meals: list["MealsMeals"]


class MealsMeals(MealFields):
    pass


Meals.model_rebuild()
