# Generated by ariadne-codegen
# Source: ./src/graphql/

from typing import Literal, Union

from pydantic import Field

from .base_model import BaseModel
from .fragments import MealLogFields


class UpdateMealLog(BaseModel):
    update_meal_log: Union[
        "UpdateMealLogUpdateMealLogMealLog",
        "UpdateMealLogUpdateMealLogObjectNotFoundError",
    ] = Field(alias="updateMealLog", discriminator="typename__")


class UpdateMealLogUpdateMealLogMealLog(MealLogFields):
    typename__: Literal["MealLog"] = Field(alias="__typename")


class UpdateMealLogUpdateMealLogObjectNotFoundError(BaseModel):
    typename__: Literal["ObjectNotFoundError"] = Field(alias="__typename")
    message: str


UpdateMealLog.model_rebuild()
