[project]
name = "eat_log_desktop"
version = "1.2.0"
requires-python = ">=3.14"
dependencies = [
    "gql",
    "pyqt6>=6.11.0",
]

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.mypy]
strict = true

[tool.uv.sources]
gql = { path = "../../shared/gql" }

[dependency-groups]
dev = [
    "mypy>=1.20.2",
    "pyinstaller>=6.21.0",
    "ruff>=0.15.12",
]
