[project]
name = "eatlog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "httpx>=0.28.0",
    "pyqt6>=6.11.0",
]

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.mypy]
strict = true

[dependency-groups]
dev = [
    "mypy>=1.20.2",
    "ruff>=0.15.12",
]
