# Generated by ariadne-codegen
# Source: ./src/graphql/

from typing import Any

from .async_base_client import AsyncBaseClient
from .get_user_by_telegram_id import GetUserByTelegramId


def gql(q: str) -> str:  # Функция разъеб, спасибо! Ставлю лосяру!"
    return q


class Client(AsyncBaseClient):
    async def get_user_by_telegram_id(
        self, telegram_id: str, **kwargs: Any
    ) -> GetUserByTelegramId:
        query = gql("""
            query GetUserByTelegramId($telegramId: String!) {
              userByTelegramId(telegramId: $telegramId) {
                __typename
                ... on User {
                  id
                  name
                  telegramId
                }
                ... on ObjectNotFoundError {
                  message
                }
              }
            }
            """)
        variables: dict[str, object] = {"telegramId": telegram_id}
        response = await self.execute(
            query=query,
            operation_name="GetUserByTelegramId",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return GetUserByTelegramId.model_validate(data)
