# Generated by ariadne-codegen
# Source: ./src/graphql/

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import Gender, Goal


class UserFields(BaseModel):
    id: Any
    name: str
    telegram_id: Optional[str] = Field(alias="telegramId")
    gender: Gender
    weight: float
    height: float
    age: int
    goal: Goal
    created_at: Any = Field(alias="createdAt")
    updated_at: Any = Field(alias="updatedAt")
    notification_time: Optional[Any] = Field(alias="notificationTime")
    hard_mod: bool = Field(alias="hardMod")


UserFields.model_rebuild()
