# Generated by ariadne-codegen
# Source: ./src/graphql/

from typing import Any, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel


class GetUserByTelegramId(BaseModel):
    user_by_telegram_id: Union[
        "GetUserByTelegramIdUserByTelegramIdUser",
        "GetUserByTelegramIdUserByTelegramIdObjectNotFoundError",
    ] = Field(alias="userByTelegramId", discriminator="typename__")


class GetUserByTelegramIdUserByTelegramIdUser(BaseModel):
    typename__: Literal["User"] = Field(alias="__typename")
    id: Any
    name: str
    telegram_id: Optional[str] = Field(alias="telegramId")


class GetUserByTelegramIdUserByTelegramIdObjectNotFoundError(BaseModel):
    typename__: Literal["ObjectNotFoundError"] = Field(alias="__typename")
    message: str


GetUserByTelegramId.model_rebuild()
