# Generated by ariadne-codegen
# Source: http://api:5285/graphql

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import Gender, Goal


class CreateUserInput(BaseModel):
    name: str
    telegram_id: Optional[str] = Field(alias="telegramId", default=None)
    gender: Gender
    weight: float
    height: float
    age: int
    goal: Goal
    notification_time: Optional[Any] = Field(alias="notificationTime", default=None)
    hard_mod: bool = Field(alias="hardMod")


class UpdateUserInput(BaseModel):
    name: Optional[str] = None
    telegram_id: Optional[str] = Field(alias="telegramId", default=None)
    gender: Optional[Gender] = None
    weight: Optional[float] = None
    height: Optional[float] = None
    age: Optional[int] = None
    goal: Optional[Goal] = None
    notification_time: Optional[Any] = Field(alias="notificationTime", default=None)
    hard_mod: Optional[bool] = Field(alias="hardMod", default=None)
