[project]
name = "eat_log_scheduler"
version = "1.0.0"
requires-python = ">=3.14"
dependencies = [
    "aiogram>=3.29.1",
    "apscheduler>=3.11.3",
    "apscheduler-stubs>=0.1.0.dev2",
    "ariadne-codegen>=0.18.0",
]

[dependency-groups]
dev = [
    "mypy>=2.2.0",
    "ruff>=0.15.20",
]

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.mypy]
strict = true

[[tool.mypy.overrides]]
module = "src.graphql.*"
ignore_errors = true

[tool.ariadne-codegen]
remote_schema_url = "http://api:5285/graphql"
queries_path = "./src/graphql/"
target_package_path = "./src/graphql/"
target_package_name = "client"
plugins = [
    "ariadne_codegen.contrib.shorter_results.ShorterResultsPlugin"
]

[tool.ariadne-codegen.scalars.UUID]
type = "uuid.UUID"

[tool.ariadne-codegen.scalars.DateTime]
type = "datetime.datetime"

[tool.ariadne-codegen.scalars.Date]
type = "datetime.date"

[tool.ariadne-codegen.scalars.Time]
type = "datetime.time"
