name: bot

on:
  pull_request:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - name: Setup uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
      - name: Setup dependencies
        working-directory: server/bot
        run: uv sync
      - name: Launch linters
        working-directory: server/bot
        run: |
          uv run ruff format --check .
          uv run ruff check .
          uv run mypy .
