name: ci

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: api
            file: ./server/api/Dockerfile
          - name: bot
            file: ./server/bot/Dockerfile
          - name: nginx
            file: ./server/nginx/Dockerfile
          - name: scheduler
            file: ./server/scheduler/Dockerfile
          - name: web
            file: ./client/web/Dockerfile
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build ${{ matrix.name }}
        uses: docker/build-push-action@v6
        with:
          file: ${{ matrix.file }}
          push: false

  lint-python:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: api
            dir: ./server/api/
          - name: bot
            dir: ./server/bot/
          - name: scheduler
            dir: ./server/scheduler/
          - name: desktop
            dir: ./client/desktop/
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
      - name: Setup dependencies and launch linters
        working-directory: ${{ matrix.dir }}
        run: |
          uv sync
          uv run ruff format --check .
          uv run ruff check .
          uv run mypy .

  lint-ts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Setup dependencies and launch linters
        working-directory: client/web
        run: |
          npm install
          npm run lint
          npm run type-check
