name: lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [server/api, server/bot, client/desktop, server/scheduler]
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
      - name: Setup dependencies
        working-directory: ${{ matrix.dir }}
        run: uv sync
      - name: Launch linters
        working-directory: ${{ matrix.dir }}
        run: |
          uv run ruff format --check .
          uv run ruff check .
          uv run mypy .
  web-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: |
          npm run lint
          npm run type-check
