name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Версия"
        required: true
        type: string
      debug:
        description: "Debug режим"
        required: true
        default: true
        type: boolean
      release_text:
        description: "Текст релиза"
        required: true
        type: string

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            ext: ""
            short_name: linux
          - os: macos-latest
            ext: ""
            short_name: mac
          - os: windows-latest
            ext: ".exe"
            short_name: windows
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
      - name: Setup dependencies
        working-directory: ./client/desktop/
        run: uv sync
      - name: Build bin
        working-directory: ./client/desktop/
        run: uv run pyinstaller ./EatLog.spec
      - name: Rename bin
        run: mv ./client/desktop/dist/* ./client/desktop/dist/EatLog-${{ inputs.version }}-${{ matrix.short_name }}${{ matrix.ext }}
      - name: Create artifact
        uses: actions/upload-artifact@v7
        with:
          name: artifact-${{ matrix.os }}
          path: ./client/desktop/dist/*
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v8
      with:
        path: ./bin/
        pattern: artifact-*
        merge-multiple: true
    - name: Ls bin dir
      run: ls ./bin/
    - name: Create release
      if: ${{ !inputs.debug }}
      uses: softprops/action-gh-release@v3
      with:
        tag_name: ${{ inputs.version }}
        body: ${{ inputs.release_text }}
        files: ./bin/*
